### PR TITLE
various fixes and new LD calculation

### PR DESCRIPTION
**Pull request by vkrajnak**
vector fields now passed in the beginning of _compute_lagrangian_descriptor_ instead of in the background

fixed issues with LD precision as _rtol_ and _atol_ seem to be applied per component and standard value was not enough

added calculation of LD via vector field, so that it is truly calculated along the trajectory

replaced scatter plot with contourf to get rid of the scatter induced blur

### CODE REVIEW

**Comment by vkrajnak** [comment]
LD now calculated correctly using the vector field (_v_ instead of _u_ in _vector_field_flat_)

_flag_m_ is now passed to _compute_lagrangian_descriptor_ as an argument and _norm_ renamed to _flag_m_ inside the function

**Comment by vkrajnak** [comment]
updated original _vector_field_flat_ to calculate LDs in the new way

**Comment by broncio123** [comment]
@vkrajnak not sure the blur is an artefact of the plotting choice.

When comparing the numeric outcomes of LD for different implementations, I found that the blur continued appearing consistently. Also, in previous (old) implementations the blur never appeared. See figures in issue #5 

> vector fields now passed in the beginning of _compute_lagrangian_descriptor_ instead of in the background
> 
> fixed issues with LD precision as _rtol_ and _atol_ seem to be applied per component and standard value was not enough
> 
> added calculation of LD via vector field, so that it is truly calculated along the trajectory
> 
> replaced scatter plot with contourf to get rid of the scatter induced blur

**Comment by broncio123** [comment]
I will do pull request to test the changes myself though. Thanks @vkrajnak

**Comment by vkrajnak** [comment]
@broncio123 We're mixing things up here. There is the inaccuracy you show in the figures in issue #5 that is local and purely due to integration. The blur is what you noticed [here](https://github.com/broncio123/lds/commit/a0ee929b03efec19819a73802ae726c55ea1b74c#commitcomment-39634231) along the edges, but in fact affects the whole figure.

**Pull request merged**
